### ISSUE TITLE
Issue with theano utils

### ISSUE THREAD

**Issue by MdAsifKhan** [hycis/bidirectional_RNN#11]
Hi,
 Latest version of keras has no support for theano utils, is there any alternative for this:
Traceback (most recent call last):
  File "cnn_blstm.py", line 28, in <module>
    from birnn import BiDirectionLSTM, Transform
  File "/home/khanma0b/keras-master/deepfunc-master/birnn.py", line 5, in <module>
    from keras.utils.theano_utils import shared_zeros, alloc_zeros_matrix
ImportError: No module named theano_utils

**Comment by hycis** [comment]
I have stopped keeping track of the latest keras, however if you want to just play with lstm, you can also checkout also mozi bilstm https://github.com/hycis/Mozi/blob/master/example/imdb_bilstm.py
It's been tested to work on a few papers.

**Comment by bennythedataguy** [comment]
all the utils stuff got moved to backend, apparently.

http://keras.io/backend/
